__author__ = "LabSid PHA EPUSP"
__email__ = "rubem.hydrological@labsid.eng.br"
__copyright__ = "Copyright 2021-2024, LabSid PHA EPUSP"
__license__ = "GPL"
__date__ = "2024-03-19"
__version__ = "1.12.3"
__release__ = __version__ + "-beta.3"
