__author__ = "LabSid PHA EPUSP"
__email__ = "rubem.hydrological@labsid.eng.br"
__copyright__ = "Copyright 2021-2022, LabSid PHA EPUSP"
__license__ = "GPL"
__date__ = "2022-02-08"
__version__ = "1.11.16"
__release__ = __version__ + "-alpha"
