__author__ = "LabSid PHA EPUSP"
__email__ = "rubem.hydrological@labsid.eng.br"
__copyright__ = "Copyright 2021-2023, LabSid PHA EPUSP"
__license__ = "GPL"
__date__ = "2023-05-17"
__version__ = "1.12.1"
__release__ = __version__ + "-beta.1"
